export const tips = [
    "try again",
    "try again again",
    "try again again again",
    "this game is not easy",
    "finesse is everything",
    "you didn't use enough finesse",
    "try to use finesse",
    "hang in there, buddy",
    "you got this",
    "this time",
    "this time",
    "for REAL this time",
    "try using finesse",
    "ya blew it",
    "ya screwed it",
    "ya lost it",
    "you couldn't make it",
    "just DO it",
    "finesse it.",
    "finesse it!",
    "oof",
    "dang it!",
    "rats!",
    "shucks!",
    "aw, heck!",
    "drat!",
    "fricking frick!",
    "argh!",
    "grrrr!",
    "reeeeeee!",
    "L",
    "another L",
    "another one",
    "and another one",
    "better luck next time",
    "is this the one?",
    "when will you win?",
    "perhaps...",
    "alas!",
    "curses!",
    "oh my!",
    "how unfortunate!",
    "unsatisfactory!",
];
