export const tips = [
    "try again",
    "try again again",
    "try again again again",
    "this game is not easy",
    "finesse is everything",
    "you didn't use enough finesse",
    "try using finesse",
    "finesse it.",
    "finesse it!",
    "try to use finesse",
    "hang in there, buddy",
    "you got this",
    "this time",
    "this time",
    "for REAL this time",
    "you missed it",
    "you blew it",
    "you whiffed it",
    "you got juked",
    "you couldn't make it",
    "just DO it",
    "oof",
    "dang it!",
    "rats!",
    "shucks!",
    "aw, heck!",
    "drat!",
    "fricking frick!",
    "argh!",
    "grrrr!",
    "reeeeeee!",
    "L",
    "another L",
    "another one",
    "and another one",
    "better luck next time",
    "is this the one?",
    "when will you win?",
    "perhaps...",
    "alas!",
    "curses!",
    "oh my!",
    "how unfortunate!",
    "unsatisfactory!",
];
